### ISSUE TITLE
Binding arguments for exchange-to-exchange binding are not set

### ISSUE THREAD

**Issue by kwispel0** [rabbitmq/hop#147]
I am using hop to configure our RabbitMQ exchanges and queues. Everything is working fine, except exchange-to-exchange bindings. The arguments do not seem to be set when applying `declareExchange`.

The following example demonstrates the issue I am seeing:

```
Client client = new Client("http://localhost:15672/api/", "admin", "admin");

client.declareExchange("my_vhost", "e1", new ExchangeInfo("headers", true, false));
client.declareExchange("my_vhost", "e2", new ExchangeInfo("fanout", true, false));

client.bindExchange("my_vhost", "e2", "e1", "#", ImmutableMap.of("my_identifier", "abc"));
```

Here, I first declare two exchanges `e1` (a headers exchange) and `e2` (a fanout exchange). Then, I want to bind `e1` -> `e2` with the header mapping `my_identifier` to `abc`. The exchanges are created as expected, but the property `my_identifier` in the binding does not seem to be set. I verified this by going to the management interface.

When creating these exchanges and binding manually in the management interface, everything is working fine.

RabbitMQ broker: 3.7.11
http-client: 3.1.0-RELEASE

**Comment by michaelklishin** [comment]
Looks like the issue is as trivial as this: the body key used to pass arguments [is `args` in Hop](https://github.com/rabbitmq/hop/blob/master/src/main/java/com/rabbitmq/http/client/Client.java#L708) and expected to be `arguments` in the HTTP API. Please submit a PR with a test?

**Comment by kwispel0** [comment]
Right, I came to the same conclusion after trying to invoke the HTTP API manually via curl.

I will submit a PR.

**Comment by kwispel0** [comment]
I am sorry, I have to correct myself. I won't be able to work on this in the short time, as my Groovy skills are basically non-existing. I currently don't have much time to invest in getting some basic Groovy knowledge.

I might be able to take this up somewhere in the beginning of March, but I would rather not promise anything as of now.

**Comment by michaelklishin** [comment]
I pushed a fix without any tests since it's a pretty trivial typo. @acogoluegnes should we reopen to add a test?

**Comment by kwispel0** [comment]
It looks like you forgot to change line https://github.com/rabbitmq/hop/blob/master/src/main/java/com/rabbitmq/http/client/Client.java#L708 as well.

**Comment by michaelklishin** [comment]
The typo was introduced 4 years ago in https://github.com/rabbitmq/hop/commit/b0e3cf03d34d7aafc77e857083c44daa39049a99 :)

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, let's re-open, I'll add a test hopefully before the end of the week.

**Comment by acogoluegnes** [comment]
This is fixed and tested for both clients. I'll cut a patch release tomorrow.

**Comment by kwispel0** [comment]
@michaelklishin and @acogoluegnes: thank's a lot
